src/app/app.component.html
src/app/app.component.ts
src/app/ng2wig/ng2wig.component.ts

output-new-content

---

package.json
src/app/app.module.ts
src/app/ng2wig/ng2wig-toolbar.service.ts
src/app/ng2wig/ng2wig.component.ts
src/app/ng2wig/ng2wig.module.ts

from importing BrowserModule to CommonModule to avoid conflicts

---

README.md

Create basic docs

---

src/tsconfig-aot.json

Add strictMetadataEmit and Closure compiler support.

Set additional build options

---

src/app/ng2wig/ng2wig.module.ts

**Problem:** With invariant check in constructor of ngwig module you only had an ability to import ngwig in **root** module
**Solution** Remove check in constructor

Add forChild, remove check in constructor

---

README.md
src/app/ng2wig/ng2wig-config.ts
src/app/ng2wig/ng2wig.component.ts
src/app/ng2wig/ng2wig.module.ts
src/index.html

- update README
- remove icon options from component, default const is in Ng2WigConfig 
- add MDI css file for testing on localhost

Refactoring

---

karma.conf.js
src/ngx-wig-toolbar.service.spec.ts
src/ngx-wig.component.spec.ts

References #34 
Configure karma to include HTML files. Add early tests for the main component

Add unit tests

---

playground/index.ts
src/ngx-wig.component.ts
src/ngx-wig.css
src/ngx-wig.html

added disabled state

---

src/ngx-wig-toolbar.service.ts
src/ngx-wig.css

https://github.com/stevermeister/ngx-wig/issues/58

Add underline support

---

src/ngx-wig-toolbar.service.spec.ts

- Modify unit test to account for new **underline** button.
- Fix typo in testing toolbar buttons length.

Fix unit test for underline button

---

src/ngx-wig.component.spec.ts

Add unit test for focusing the editor according to #60

Add focus test

---

projects/ngx-wig/src/lib/ngx-wig-toolbar.service.spec.ts
projects/ngx-wig/src/lib/ngx-wig.component.spec.ts

- Modify page class according to [angular.io](https://angular.io/guide/testing#use-a-page-object) described techniques.
- Enable the **disabled property** test.
- Fix minor **tslint** rules

Modify more tests

---

projects/ngx-wig/src/lib/ngx-wig.component.spec.ts

Add more test cases according to the interaction with the template

Fix tests according to the template

---

projects/ngx-wig/src/lib/ngx-wig.component.spec.ts

Add unit test to check behavior of external components with `ngModel`

Add test for ngModel interaction

---

projects/ngx-wig/src/lib/ngx-wig.component.spec.ts

@stevermeister that's all the tests :smiley:

Add remaining tests for component

---

projects/ngx-wig/src/lib/ngx-wig.component.ts
src/polyfills.ts

On IE `input` event is not triggered on `contenteditable div` and `valueChanges` is not fired. In this fix I use `MutationObserver` to listen text changes.

[hotfix] fix valueChanges for ie11

---

README.md

Plugin demo

---

package-lock.json
package.json
projects/ngx-wig/src/lib/ngx-wig.component.spec.ts
projects/ngx-wig/src/lib/ngx-wig.component.ts
tsconfig.json

@stevermeister I have upgraded the library to Angular 8. Could you please have a look? There are also some points that need to be discussed:
1. I have noticed that we reference `@angular-devkit/build-ng-packagr` and `tsickle` in the `package.json`. Do we use them outside of the CLI?
2. With the advent of Angular 8, differential loading came along. Do you think turning this on will benefit our users?

Upgrade to Angular 8

---

README.md
projects/ngx-wig/src/lib/config.ts
src/app/app.component.ts

Fix tslint rules according to #113 . Update README to indicate how to run tests.

Fix minor tslint rules and add guide how to run tests

---

.github/workflows/main.yml

@stevermeister we had a discussion some time ago about moving to GitHub actions. This PR introduces GitHub actions to the repo by adding a new action that runs unit tests when a PR is submitted.

Create CI action for testing

---

projects/ngx-wig/src/lib/ngx-wig-component.html

Hi, I tried to improve the interaction with the drop-down menu after some complaints. I moved the opening and closing of the menu from the button click to the mouse focus (mouseenter and mouseleave). I hope this will be useful.

Improving dropdown animation

---

projects/ngx-wig/src/lib/ngx-wig-component.html

This PR fixes a cherry pick, meant to backport #180 changes to an older version (13.1.6) of the package

Excluded changes from commit 8c4f4fcd7d4711908d11a8abd741e2ea9f5241c4
